# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ "main", "development" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Checkout Common Library Dependency
        uses: actions/checkout@v3
        with:
          repository: '5G-MAG/rt-5gms-common-android-library'
          ref: 'development'
      - name: Publish Common Library to MavenLocal
        run: ./gradlew publishToMavenLocal
      - name: Checkout Media Stream Handler Dependency
        uses: actions/checkout@v3
        with:
          repository: '5G-MAG/rt-5gms-media-stream-handler'
          ref: 'development'
      - name: Publish Media Stream Handler to MavenLocal
        run: ./gradlew publishToMavenLocal
      - name: Checkout main repo
        uses: actions/checkout@v3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
          build-root-directory: fivegmag_5GMSdAwareApplication